import { arraySidebar } from "vuepress-theme-hope";

export const baseInterview = arraySidebar([
    "",
    {
        text: "分章节",
        icon: "creative",
        collapsable: true,
        children: [
            "the_interview_questions_lite_version",
            "HTML",
            "CSS",
            "JavaScript",
            "jQuery",
            "Ajax",
            "HTTP",
            "Front-end-frame-relative",
            "Json-XML",
            "localStorage",
            "mobile-terminal",
            "Modules",
            "performance-optimization",
            "PS",
            "SEO",
            "ES6",
            "cross-domain",
            "cookie",
            "MVC",
            "Git",
            "data-structure",
            "dataBase",
            "Handwritten-code",
            "computer-basic-knowledge",
            "other",
            "comprehensive",
            "vue",
            "react",
            "MVVM",
            "the_browser",
            "performance",
            "CSRF_and_XSS",
            "createObj_and_the_prototype_chain",
            "crossdomain_communication_class",
            "objectoriented",
            "the_frontend_monitoring_errors",
            "the_page_layout",
            "CSS_box_and_BFC",
            "dom_events_summary",
            "http_protocol",
        ],
    },
    {
        text: "综合版本",
        icon: "creative",
        collapsable: true,
        children: [
            "question-version",
            "question-and-answer-version",
        ],
    },

]);